version: '2'

volumes:
  yadda_data:
  yadda_repo_data:

services:
  yadda:
    image: saizo/yadda:dev
    env_file: ./.yadda/yadda.env
    volumes:
      - yadda_repo_data:/data/repo
    links:
      - yaddadb
  nginx:
    image: saizo/yadda_nginx:dev
    ports:
      - "443:443"
    links:
      - "yadda"
  yaddadb:
    image: mongo:latest
    env_file: ./.yadda/mongodb.env
    volumes:
      - yadda_data:/data/db
    ports:
      - "27017:27017"
