FROM mongo
MAINTAINER Jason Ozias <jason.g.ozias@gmail.com>

RUN apt-get update && apt-get install -y wget
ENV DOCKERIZE_VERSION v0.2.0
RUN wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz

COPY config/db db

CMD dockerize -wait tcp://ellmakdb:27017 mongo --host ellmakdb --eval "db.dropDatabase()" ellmak && mongorestore -h ellmakdb -d ellmak db/ellmak
