version: '2'

services:
  ellmak:
    build: .
    image: saizo/ellmak:local
    volumes:
      - ./api/dist:/usr/src/ellmak/dist
    environment:
      - ELLMAK_CORS_WHITELIST=http://localhost:8080
    ports:
      - "3000:3000"
  nginx:
    image: nginx:latest
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./.ellmak/ssl:/etc/nginx/ssl:ro
      - ./ui/dist:/www/data
  ellmakdb-seed:
    build:
      context: .
      dockerfile: Dockerfile.seed
    env_file: ./.ellmak/mongodb.env
    image: saizo/ellmak-seed:local
    links:
      - "ellmakdb"
