version: '2'

volumes:
  ellmak_data:
  ellmak_repo_data:

services:
  ellmak:
    image: saizo/ellmak:dev
    env_file: ./.ellmak/ellmak.env
    volumes:
      - ellmak_repo_data:/data/repo
    links:
      - ellmakdb
  nginx:
    image: saizo/ellmak_nginx:dev
    ports:
      - "443:443"
    links:
      - "ellmak"
  ellmakdb:
    image: mongo:latest
    command: [ "mongod", "--auth" ]
    env_file: ./.ellmak/mongodb.env
    volumes:
      - ellmak_data:/data/db
    ports:
      - "27017:27017"
