version: '2'

services:
  yadda:
    build: .
    image: saizo/yadda:local
    volumes:
      - ./api/dist:/usr/src/yadda/dist
    environment:
      - YADDA_CORS_WHITELIST=http://localhost:3000,http://localhost:8080
    ports:
      - "3000:3000"
  nginx:
    image: nginx:latest
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./.yadda/ssl:/etc/nginx/ssl:ro
      - ./ui/dist:/www/data
  yaddadb-seed:
    build:
      context: .
      dockerfile: Dockerfile.seed
    image: saizo/yadda-seed:local
    links:
      - "yaddadb"
