#!/usr/bin/python3
import argparse
import os
from os import environ
from subprocess import check_call

# Store the current directory
owd = os.getcwd()

# Setup the supported command-line arguments
parser = argparse.ArgumentParser(description='Push project Docker images')
parser.add_argument('-n', '--nginx', help='Turn off nginx build', action="store_true")
parser.add_argument('-y', '--ellmak', help='Turn off ellmak build', action="store_true")

# Parse the command-line arguments
args = parser.parse_args()

# Change working directory
os.chdir(os.path.join(os.path.dirname( __file__ ), '..' ))

if not args.nginx:
  print('Pushing ellmak nginx image')
  check_call(["docker", "push", "saizo/ellmak_nginx:dev"])

if not args.ellmak:
  print('Pushing ellmak image')
  check_call(["docker", "push", "saizo/ellmak:dev"])

# Change back to the original directory
os.chdir(owd)
